version: '3'

services:
  server1:
    image: ${NEO4J_DOCKER_IMAGE}

    # Hostname
    hostname: server1

    network_mode: "host"

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - ./neo4j.conf:/conf/neo4j.conf # This is the main configuration file.
      - ./app/data:/var/lib/neo4j/data
      - ./app/data:/var/lib/neo4j/import

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      - NEO4J_initial_server_mode__constraint=PRIMARY

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

    # Set up the user
    user: ${USER_ID}:${GROUP_ID}
